### ISSUE TITLE
a bad error comes after each player connects to server

### ISSUE THREAD

**Issue by Harry755** [wasabirobby/fivem-appearance#10]
script:fivem-appeara] SCRIPT ERROR: @fivem-appearance/server.lua:22: attempt to index a nil value (local 'xPlayer')
[script:fivem-appeara] > TriggerServerCallback (@es_extended/server/functions.lua:160)
[script:fivem-appeara] > handler (@es_extended/server/common.lua:124)

**Comment by wasabirobby** [comment]
Try latest push

**Comment by Itzmezzzzz** [comment]
> Try latest push

hey still the same error comes on latest update too 
whenever a player creates a character this error comes
