### ISSUE TITLE
Charging money for buying outfit

### ISSUE THREAD

**Issue by stoopidduck** [wasabirobby/fivem-appearance#20]
Hi,

I'd like to know if there is a chance to add a price when a player buys a new outfit.

In the clothes shop, barber and tattoo.

Thanks.

**Comment by mr-capy** [comment]
**done download latest version**

> Hi,
> 
> I'd like to know if there is a chance to add a price when a player buys a new outfit.
> 
> In the clothes shop, barber and tattoo.
> 
> Thanks.

**Comment by stoopidduck** [comment]
Thanks!
