### ISSUE TITLE
Make tattoo shop options not pick and show

### ISSUE THREAD

**Issue by stoopidduck** [wasabirobby/fivem-appearance#23]
Hi,

Sorry for being so picky, but, is there a way the tattoo menu could be more like a list?

I mean, now is hard to go one by one to see the tattoo on the body.

It would be awesome to beable to just click down arrow and see all the tattoos going by so people dont take forever to choose one.

Thanks in advanced.

**Comment by wasabirobby** [comment]
Wish but I am not the UI developer, I only added the framework dependencies and Lua portion of the script.
