### ISSUE TITLE
feat. request: Add more Labels for Clothe-Shops

### ISSUE THREAD

**Issue by Marc85BPG** [wasabirobby/fivem-appearance#27]
Hey there,
ya like the Title, an option for make as an example "suburban" / "Binco" and "Ponsonbys"

got here an description:
"There are only three types of stores: cheap (normal clothes, sometimes the same like in Binco but cheaper), Binco (sports, normal clothing), Suburban (more relaxed clothes) and Ponsonboys (expensive, luxury clothes - suits, shirts etc)."

Also it would be nice to configure Mask Shop separately aswell as Glasses Shop and Bags Shop.

Greetings

**Comment by wasabirobby** [comment]
Check latest update for this feature
