### ISSUE TITLE
Bug: Tattoos and Appearance from Main Char goes to the Multichar 

### ISSUE THREAD

**Issue by Marc85BPG** [wasabirobby/fivem-appearance#28]
Have a Bug here:

* If you Configure a Main Char with Tattoos, and you make a Secon or Third Char, the Tattoos get duplicated.
* If you Press The Delete Button on you Second Char (Multichar) it have on Preview the same Appearance as the Main-Char.

Regards

**Comment by wasabirobby** [comment]
Try latest version
