### ISSUE TITLE
Fade's don't work

### ISSUE THREAD

**Issue by FBFezz** [wasabirobby/fivem-appearance#3]
Unsure why but the fade's (haircuts) don't actually work for some reason, unsure why but im going to look into it

**Comment by SpalenyBramborak** [comment]
Are you sure that you wrote this convar in your server.cfg? 

setr fivem-appearance:automaticFade 1

This convar activates fade in the menu.

**Comment by FBFezz** [comment]
Nah i havn't as it isnt in the docs page or anything, will try it now, thanks

**Comment by wasabirobby** [comment]
I was about to message you about this convar. It’s in original documentation. I will update the fork’s documentation with useful convar settings as few have had complications with the locales as well.

**Comment by FBFezz** [comment]
> Are you sure that you wrote this convar in your server.cfg?
> 
> setr fivem-appearance:automaticFade 0
> 
> This convar activates fade in the menu.

This was the fix
