### ISSUE TITLE
Tattoos won't save

### ISSUE THREAD

**Issue by stoopidduck** [wasabirobby/fivem-appearance#32]
Hi,

In the lastest version, tattoos won't get saved on skin even if you pay them.

**Comment by zRxnx** [comment]
Do you also press on "save" ?

**Comment by stoopidduck** [comment]
Yes, we press save, it charges you, but the tattoo won't stay on your body

**Comment by wasabirobby** [comment]
Are you using additional tattoo script such as rcore, etc?
