### ISSUE TITLE
index a nil value (local 'appearance')

### ISSUE THREAD

**Issue by dim62** [wasabirobby/fivem-appearance#37]
![image](https://user-images.githubusercontent.com/91420869/201412906-d46c06b5-5015-4d10-9e53-7048c0046bb7.png)

**Comment by TheGoatRico** [comment]
Im getting this same error

**Comment by AlminBP76** [comment]
anyone have a  solution for this?

**Comment by wasabirobby** [comment]
Try latest or see discord for support
