### ISSUE TITLE
Blip name didn't support my languages

### ISSUE THREAD

**Issue by DyroS3** [wasabirobby/fivem-appearance#38]
I see something wrong when I used the latest, when I change the `string` code ,change ENG to Chinese, the name will be empty.But I when I use the vesion 1.0.5 ,then it work good.   I don't kown what happend,hope U could write back

**Comment by wasabirobby** [comment]
Does your language work with other blips in other scripts?

**Comment by dingyu1126** [comment]
yep,only test the latest version,that didn't work

**Comment by wasabirobby** [comment]
Fixed in latest
