### ISSUE TITLE
Issue: Always start with an "Male" Ped - even if you say "Female" in esx_identity

### ISSUE THREAD

**Issue by Marc85BPG** [wasabirobby/fivem-appearance#42]
If you create a character with esx_identity you get into the Char-Creation with an Male Ped.
Even if you Press on Female.

I Personally hide the "Ped-Selection" in the Char creator because it is not really Roleplay friendly to offer other Players to select any Ped in GTA-Lore.
This will be abused by Players for 10000%

So is there a solution when i press on Female -> preselect the Female Ped
and if you Select Male -> Preselect the Male Ped.

**Comment by wasabirobby** [comment]
Try latest version
