### ISSUE TITLE
Hair and Face features dont save or load with outfits

### ISSUE THREAD

**Issue by LabScripts** [wasabirobby/fivem-appearance#45]
Hey there! I've noticed that face features, along with hair, skin colour etc, do not save (or load) with outfits.
If you save an outfit, load another, then load the outfit you just saved, it only loads your clothes.

**Comment by LabScripts** [comment]
I've made a fix for that, I'll commit the changes asap

**Comment by wasabirobby** [comment]
Thank you for this!
