### ISSUE TITLE
Tattoos and fades disappearing

### ISSUE THREAD

**Issue by JustDeltaAU** [wasabirobby/fivem-appearance#5]
Occasionally (can't get it to happen every time) when you leave the clothing store without changing or saving anything it removes tattoos and fades.

**Comment by wasabirobby** [comment]
Although I am not positive this will be the remedy; have you tried adding this to your server convars?

setr fivem-appearance:automaticFade 0

**Comment by JustDeltaAU** [comment]
Yeah I have that.

It doesn't always do it, but it seems to just completely wipe tattoo/fade data as soon as you exit out of the clothing shop if you don't save.
