### ISSUE TITLE
language FR+ add 

### ISSUE THREAD

**Issue by Mesrine67** [wasabirobby/fivem-appearance#57]
{
  "modal": {
    "save": {
      "title": "Enregistrer ?",
      "description": "Tu resteras moche"
    },
    "exit": {
      "title": "Annuler",
      "description": "Aucune modification ne sera enregistrée"
    },
    "accept": "Oui",
    "decline": "Non"
  },
  "ped": {
    "title": "Ped",
    "model": "Model"
  },
  "headBlend": {
    "title": "Héritage",
    "shape": {
      "title": "Visage",
      "firstOption": "Père",
      "secondOption": "Mère",
      "mix": "Mélange"
    },
    "skin": {
      "title": "Skin",
      "firstOption": "Père",
      "secondOption": "Mère",
      "mix": "Mélange"
    }
  },
  "faceFeatures": {
    "title": "Caractéristiques du visage",
    "nose": {
      "title": "Nez",
      "width": "Largeur",
      "height": "Hauteur",
      "size": "Taille",
      "boneHeight": "Hauteur",
      "boneTwist": "Torsion",
      "peakHeight": "Hauteur maximale"
    },
    "eyebrows": {
      "title": "Sourcils",
      "height": "Hauteur",
      "depth": "Profondeur"
    },
    "cheeks": {
      "title": "Joues",
      "boneHeight": "Hauteur",
      "boneWidth": "Largeur",
      "width": "Largeur 2"
    },
    "eyesAndMouth": {
      "title": "Yeux et bouche",
      "eyesOpening": "Bridage des yeux",
      "lipsThickness": "Épaisseur des lèvres"
    },
    "jaw": {
      "title": "Mâchoire",
      "width": "Largeur",
      "size": "Taille"
    },
    "chin": {
      "title": "Menton",
      "lowering": "Abaissement",
      "length": "Longueur",
      "size": "Taille",
      "hole": "Taille du trou"
    },
    "neck": {
      "title": "Cou",
      "thickness": "Épaisseur"
    }
  },
  "headOverlays": {
    "title": "Apparence",
    "hair": {
      "title": "Cheveux",
      "style": "Style",
      "color": "Couleur",
      "highlight": "Souligner", 
      "fade": "Ride"
    },
    "opacity": "Opacité",
    "style": "Style",
    "color": "Couleur",
    "blemishes": "Défauts",
    "beard": "Barbe",
    "eyebrows": "Sourcils",
    "ageing": "Vieillissement",
    "makeUp": "Maquillage",
    "blush": "Blush",
    "complexion": "Teint",
    "sunDamage": "Dommages causés par le soleil",
    "lipstick": "Rouge à lèvres",
    "moleAndFreckles": "Taupe et taches de rousseur",
    "chestHair": "Poil",
    "bodyBlemishes": "Défauts corporels",
    "eyeColor": "Couleur des yeux"
  },
  "components": {
    "title": "Vêtement",
    "drawable": "Variable",
    "texture": "Texture",
    "mask": "Masque",
    "upperBody": "Mains",
    "lowerBody": "Jambes",
    "bags": "Sacs et parachute",
    "shoes": "Chaussures",
    "scarfAndChains": "Foulard et chaînes",
    "shirt": "Chemise",
    "bodyArmor": "Gilets pare-balles",
    "decals": "Décalcomanies",
    "jackets": "Vestes"
  },
  "props": {
    "title": "Accessoires",
    "drawable": "Variable",
    "texture": "Texture",
    "hats": "Chapeaux et casques",
    "glasses": "Lunettes",
    "ear": "Oreille",
    "watches": "Montres",
    "bracelets": "Bracelets"
  }, 
  "tattoos": {
    "title": "Tattoos",
    "items": {
      "ZONE_TORSO": "Torse",
      "ZONE_HEAD": "Tête",
      "ZONE_LEFT_ARM": "Bras gauche",
      "ZONE_RIGHT_ARM": "Bras droit",
      "ZONE_LEFT_LEG": "Jambe gauche",
      "ZONE_RIGHT_LEG": "Jambe droite"
    },
    "apply": "Appliquer", 
    "delete": "Supprimer"
  }
}

**Comment by wasabirobby** [comment]
Thank you very much, please upload to PR
