### ISSUE TITLE
Problems with removing clothes

### ISSUE THREAD

**Issue by ItsManueh** [wasabirobby/fivem-appearance#58]
When I click to remove the clothes to put on the tattoos, I get the character with clothes that I have to touch so that he is in his underwear.

With the old skinchanger script it will be fixed but here in the
fivem-appearance I don't know how to do it if someone can help me fix this, I would appreciate it a lot.

![Sin título](https://user-images.githubusercontent.com/47420352/207673360-7fef99da-4360-4b45-b850-998c0afbc2c1.png)

**Comment by CommanderBALA** [comment]
How did you fix that?
